apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-refresh-website-deployment
  labels:
    app: {{ .Chart.Name }}-refresh-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-refresh-website
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-refresh-website
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: {{ .Chart.Name }}-container-registry-secret
      containers:
        - name: {{ .Chart.Name }}-refresh-website
          image: {{ index .Values.werf.image "covid-vaccine-spotter" }}
          args: ["bin/refresh-website"]
          env:
            - name: LOG_LEVEL
              value: notice
            - name: PUBLISH_SITE
              value: "true"
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-secrets
